resources:

# source repository containing
# - concourse pipeline
# - docker file with nginx container
- name: concourse-nginx
  type: git
  icon: git
  source:
    uri: https://github.com/rockhowse/concourse-nginx.git
    branch: testing-additional-tags

# information required to connect to a docker registry and publish the image
- name: nginx-docker-image
  type: docker-image
  icon: docker
  source:
    username: ((registry-username))
    password: ((registry-password))
    repository: ((repository-name))/concourse-nginx
    # this example assumes http connectivity to jfrog artifactory deployed using the default helm chart 
    # it's using the CoreDNS default internal k8s cluster DNS, which IS NOT SUITABLE FOR PRODUCTION
    insecure_registries: ["jfrog-platform-artifactory-nginx.jfrog-platform.svc.cluster.local:80"]
    
jobs:
- name: publish
  public: true
  serial: true
  plan:
  # pull the github repository
  - get: concourse-nginx
    trigger: true
  # build and push the docker image to the image repository
  - put: nginx-docker-image
    params:
      build: concourse-nginx
      additional_tags: additional_tags